# Generated by Django 4.1.7 on 2023-03-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.CharField(max_length=20)),
                ('begin_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('hotel_name', models.CharField(max_length=20)),
                ('room_location', models.CharField(max_length=15, unique=True)),
                ('emergency_contact_name', models.CharField(max_length=20)),
                ('emergency_contact_cellpohne_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.CharField(max_length=20)),
                ('hotel_name', models.CharField(max_length=20, unique=True)),
                ('enable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('room_location', models.CharField(blank=True, max_length=15, unique=True)),
                ('enable', models.BooleanField()),
                ('booking', models.BooleanField()),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='travel_agency_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('document_type', models.CharField(max_length=20)),
                ('document_number', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('cellphone_number', models.IntegerField(unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.booking')),
            ],
        ),
    ]
