# Generated by Django 4.1.7 on 2023-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_location',
            field=models.CharField(max_length=15),
        ),
    ]
