# Generated by Django 4.1.7 on 2023-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0002_alter_room_room_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_location',
            field=models.CharField(max_length=15),
        ),
    ]
