# Generated by Django 4.1.7 on 2023-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0003_alter_booking_room_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=20, unique=True)),
                ('enable', models.BooleanField()),
            ],
        ),
    ]
