# Generated by Django 4.1.7 on 2023-03-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.city'),
        ),
    ]
