# Generated by Django 4.1.7 on 2023-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0005_hotel_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='cellphone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='document_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
